version: '0'

services:
  facade:
    build: ./facade
    ports:
      - "8000:8000"
    env_file:
      - ./facade/.env
    depends_on:
      - message
      - logging

  message:
    build: ./message
    ports:
      - "8001:8000"
    env_file:
      - ./message/.env

  logging:
    build: ./logging
    ports:
      - "8002:8000"
    env_file:
      - ./logging/.env