version: '0'

services:
  facade:
    build: ./facade
    ports:
      - "8000:8000"
    env_file:
      - ./facade/.env
    depends_on:
      - message
      - logging

  message:
    build: ./message
    ports:
      - "8001:8000"
    env_file:
      - ./message/.env

  logging:
    build: ./logging
    ports:
      - "8002:8000"
    env_file:
      - ./logging/.env
    networks:
      - logging-network

  logging-db-node-1:
    image: hazelcast/hazelcast:5.2.1
    container_name: logging-db-node-1
    ports:
    - "5701:5701"
    networks:
    - logging-network
    environment:
    - HZ_CLUSTERNAME=hz_cls

  logging-db-node-2:
    image: hazelcast/hazelcast:5.2.1
    container_name: logging-db-node-2
    ports:
    - "5702:5701"
    networks:
    - logging-network
    environment:
    - HZ_CLUSTERNAME=hz_cls
  
  logging-db-node-3:
    image: hazelcast/hazelcast:5.2.1
    container_name: logging-db-node-3
    ports:
    - "5703:5701"
    networks:
    - logging-network
    environment:
    - HZ_CLUSTERNAME=hz_cls

  logging-management-center:
    image: hazelcast/management-center:5.2.1
    container_name: logging-management-center
    volumes:
      - /opt/hazelcast/config.yml
    ports:
    - "9000:8080"
    environment:
    - HZ_CLUSTERNAME=hz_cls
    networks:
    - logging-network

networks:
  logging-network:
    name: logging-network